# Generated by Django 2.1.1 on 2018-09-25 12:39

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('df_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('cover', models.ImageField(default='static/images/banner02.jpg', upload_to='static/goods/GoodsInfo/cover')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('isDelete', models.BooleanField(default=False)),
                ('unit', models.CharField(max_length=32)),
                ('click', models.IntegerField()),
                ('synopsis', models.CharField(max_length=220)),
                ('repertory', models.IntegerField()),
                ('introduce', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='GoodsTypeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('icon', models.ImageField(default='static/images/banner02.jpg', upload_to='static/goods/GoodTypeInfo/icon')),
                ('cover', models.ImageField(default='static/images/banner02.jpg', upload_to='static/goods/GoodTypeInfo/cover')),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RecentGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GoodsInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_goods.GoodsInfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_user.UserInfo')),
            ],
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='goods_type_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_goods.GoodsTypeInfo'),
        ),
    ]
