# Generated by Django 2.1.1 on 2018-09-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0002_auto_20180928_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='harvestName',
        ),
        migrations.AddField(
            model_name='harvestaddress',
            name='harvestName',
            field=models.CharField(default='', max_length=32),
        ),
    ]
