# Generated by Django 2.1.1 on 2018-09-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0003_auto_20180928_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='harvestaddress',
            old_name='address',
            new_name='harvestAddress',
        ),
        migrations.AddField(
            model_name='harvestaddress',
            name='harvestPhone',
            field=models.CharField(default='', max_length=32),
        ),
    ]
