# Generated by Django 2.1.1 on 2018-09-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='count',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
