# Generated by Django 2.1.1 on 2018-09-29 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_order', '0002_orderlist_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlist',
            old_name='count',
            new_name='amount',
        ),
    ]
